<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HotelAgentIA.Application\HotelAgentIA.Application.csproj" />
    <ProjectReference Include="..\HotelAgentIA.Infrastructure\HotelAgentIA.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
